<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class umkms extends Model
{
    //
    protected $fillable = [
        'nama_usaha',
            'bentuk_usaha',
            'tahun_usaha',
            'tahun_usaha',
            'omset',
            'bidang_usaha',
            'no_telp_usaha',
            'jenis_produk',
            'foto_produk',
            'bahan_baku',
            'kebutuhan_bahan',
            'nama_merk',
            'deskripsi_produk',
            'variasi_produk',
            'deskripsi_usaha',
            'karyawan_tetap_pria',
            'karyawan_tidak_tetap_pria',
            'karyawan_tetap_wanita',
            'karyawan_tidak_tetap_wanita',
            'nama_pengurus',
            'kontak',
            'jabatan',
            'no_ktp_pj',
            'nama_lengkap',
            'email',
            'alamat',
            'provinsi',
            'kota',
            'desa',
            'kode_pos',
            'no_telp_rumah',
            'no_hp',
            'no_ktp',
            'foto_ktp',
            'foto_pj',
            'alamat_usaha_utama',
            'provinsi_usaha',
            'kota_usaha',
            'alamat_usaha_lain',
            'alamat_usaha_lain2',
            'iumk',
            'sku',
            'izin_usaha_industri',
            'surat_ijin',
            'npwp_pemilik',
            'npwp_bu',
            'sk_usaha',
            'tdup',
            'akta_usaha',
            'imb',
            'tanpaberkas',
            'foto_iumk',
            'foto_sku',
            'foto_izin_usaha_industri',
            'foto_surat_ijin',
            'foto_npwp_pemilik',
            'foto_npwp_bu',
            'foto_sk_usaha',
            'foto_tdup',
            'foto_akta_usaha',
            'pirt',
            'sh',
            'sni',
            'izin_alat_kesehatan',
            'pkrt' ,
            'iso',
            'keamanan' ,
            'halal',
            'bpom',
            'sertifikat_khusus_pangan',
            'sertifikat_non_pangan',
            'tanpa_sertifikat',
            'foto_pirt',
            'foto_sh',
            'foto_sni',
            'foto_izin_alat_kesehatan',
            'foto_pkrt',
            'foto_iso',
            'foto_keamanan',
            'foto_halal',
            'foto_bpom',
            'foto_sertifikat_khusus_pangan',
            'foto_sertifikat_non_pangan',
            'website',
            'sosmed',
            'link_sosmed',
            'marketplace',
            'link_marketplace',
            'nama_mentor',
            'kontak_mentor',
            'jenis_kontak_mentor',
            'asosiasi_komunitas' ,
            'nama_organisasi',
    ];
}
